version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fastapi-api
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   environment:
  #     PYTHONDONTWRITEBYTECODE: "1"
  #     PYTHONUNBUFFERED: "1"
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #   command: >
  #     uvicorn app.main:app
  #     --host 0.0.0.0
  #     --port 8000
  #     --reload
